services:
  backend-apigate:
    build:
      context: ./backend-apigate
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    tty: true
    develop:
      watch:
        - action: sync
          path: ./backend-apigate
          target: /app/
          ignore:
            - .git/
