services:
  backend-apigate:
    build:
      context: ./backend-apigate
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    tty: true
    # DB接続情報を環境変数として渡す
    environment:
      - DATABASE_URL=postgres://app_user:password@db:5432/app_db?sslmode=disable
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend-apigate
          target: /app/
          ignore:
            - .git/
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    command: ["pnpm", "dev"]
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
            - .git
            - .vscode
        - action: rebuild
          path: ./package.json

volumes:
  pnpm-store:
  postgres-data:
