openapi: 3.0.3
info:
  title: Bulletin Board API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /posts:
    get:
      summary: Get all posts
      operationId: getPosts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create a new post
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
          x-go-type: googleuuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
            name: googleuuid
          format: uuid
          example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
        title:
          type: string
          example: 'My First Post'
        content:
          type: string
          example: 'This is the content of the post.'
        created_at:
          type: string
          format: date-time
          example: '2025-07-07T10:00:00Z'

    NewPost:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          example: 'My New Post Title'
        content:
          type: string
          example: 'Content for the new post.'

    Error:
      type: object
      properties:
        message:
          type: string
