name: Go Ci
on:
  push:
    branches: [ main ]
    paths:
      - "backend-apigate/**"
      - ".github/workflows/go_ci.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - "backend-apigate/**"
      - ".github/workflows/go_ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-apigate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: |
          cd backend
          go mod download
      - name: Run tests
        run: |
          cd backend
          go test ./...
