name: Next.js CI
on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/next_ci.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/next_ci.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: pnpm/action-setup@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Build Next.js application
        run: |
          pnpm build
      - name: Run tests
        run: |
          pnpm test --run
      - name: Lint code
        run: |
          pnpm check
